function[X, T] = get_sets(d, len) 
cd = 1.0 -d; % 1 - deviation
offset = 2 * d;
X = [(rand([2, len]).*offset)-d ...
     [(rand([1, len]).*offset)-d; (rand([1, len]).*offset)+cd] ...
     [(rand([1, len]).*offset)+cd; (rand([1, len]).*offset)-d] ...
     (rand([2, len]).*offset)+cd];
 
T = [zeros(1, len) ...
     zeros(1, len) ...
     zeros(1, len) ...
     ones(1, len)];


 